export const FETCH_DISCOGRAPHIES = "FETCH_DISCOGRAPHIES";
export const FETCH_DISCOGRAPHIES_SUCESS = "FETCH_DISCOGRAPHIES_SUCESS";
export const FETCH_DISCOGRAPHIES_FAILURE = "FETCH_DISCOGRAPHIES_FAILURE";
